__author__ = 'luca'
import settings

DJANGO_CUISINE_INGREDIENT_EXTRA = getattr(settings, 'DJANGO_CUISINE_INGREDIENT_EXTRA', 2)
DJANGO_CUISINE_INGREDIENT_MAX_NUM = getattr(settings, 'DJANGO_CUISINE_INGREDIENT_MAX_NUM', 20)
DJANGO_CUISINE_RECIPE_STEPS_EXTRA = getattr(settings, 'DJANGO_CUISINE_RECIPE_STEPS_EXTRA',3)
DJANGO_CUISINE_RECIPE_STEPS_MAX_NUM = getattr(settings, 'DJANGO_CUISINE_RECIPE_STEPS_MAX_NUM', 15)
